apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: validator-resources
spec:
  project: app-val
  source:
    repoURL: https://github.com/Bidon15/celestia-node-cluster.git
    path: apps/validator
    targetRevision: main
  destination:
    namespace: validator
    name: in-cluster
  syncPolicy:
    automated: {}
---
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: validator-resources
spec:
  sourceRepos:
    - https://github.com/Bidon15/celestia-node-cluster.git
  destinations:
    - namespace: '*'
      name: in-cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'