apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-controller
spec:
  project: app-val
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.8.0
    helm:
      values: |
        controller:
          replicaCount: 1
          service:
            type: LoadBalancer
  destination:
    namespace: ingress-nginx
    name: in-cluster
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingress-nginx-controller
spec:
  sourceRepos:
    - https://github.com/Bidon15/celestia-node-cluster.git
  destinations:
    - namespace: '*'
      name: in-cluster
    - namespace: '*'
      name: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'